[features]
seeds = false
skip-lint = false

[programs.devnet]
aperture_gateway = "C2q9yxux7b7bxFF64pkZUV6g2Vcs2bQ1FS4GUQy512wv"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "python backend/test_security.py"
