[features]
seeds = false
skip-lint = false

[programs.devnet]
aperture_gateway = "A5HfdyRWy77i5DxhTMBa1ZinxVGZbVZnb35EvXUvkNzQ"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "python backend/test_security.py"
